# Generated by Django 5.1.1 on 2024-10-05 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scamclothes', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='user/%Y/%m/d'),
        ),
    ]
